apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hostpath
  labels:
    app: nginx-hostpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hostpath
  template:
    metadata:
      labels:
        app: nginx-hostpath
    spec:
      volumes:
        - name: nginx-html
          hostPath:
            path: /mnt/hostPath
            type: DirectoryOrCreate
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
              name: "http-server"
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
